- name: Create config
  community.docker.docker_config:
    name: "glance_{{ item | basename | splitext | first }}_{{ (lookup('file', item) | hash('sha256'))[:7] }}"
    data: "{{ lookup('file', item) }}"
  with_fileglob:
    - "{{ role_path }}/files/*.yml"

- name: Deploy stack
  community.docker.docker_stack:
    name: glance
    compose: ["{{ lookup('template', 'stack.yml') | from_yaml }}"]
  notify: Prune Docker images
