version: 2
updates:
  - package-ecosystem: docker-compose
    directories: ["/roles/*/templates"]
    schedule:
      interval: daily

  - package-ecosystem: docker
    directories: ["/roles/*/files"]
    schedule:
      interval: daily
