[settings]
disable_backends = ["asdf"] # cannot be updated by Renovate

[tools]
ansible = { version = "latest", uvx = true, uvx_args = "--with-executables-from ansible-core,ansible-lint" }
"pipx:cruft" = "latest"
uv = "latest"

[tasks]
ping = { run = "ansible all -m ping", description = "Check inventory" }
lint = { run = "ansible-lint site.yml", description = "Lint playbook" }
deploy = { run = "ansible-playbook site.yml", description = "Run playbook" }
"ssh:copy-id" = { usage = 'arg "<host>"', run = 'ssh-copy-id "$usage_host"', description = "Copy SSH key to host" }
"vault:password" = { shell = "bash -c", run = 'read -rsp "Vault password: " password && echo && printf "%s\n" "$password" > vault/.password', description = "Set the Vault password" }
"vault:decrypt" = { usage = 'arg "<file>"', run = 'ansible-vault decrypt "$usage_file"', description = "Decrypt a Vault file" }
"vault:encrypt" = { usage = 'arg "<file>"', run = 'ansible-vault encrypt "$usage_file"', description = "Encrypt a Vault file" }
"template:update" = { run = "cruft update", description = "Update project with the latest changes from the template" }
"template:restore" = { run = "cruft diff | git apply", description = "Restore template-managed files" }
