- name: Configure Swarm
  hosts: swarm
  become: true
  roles:
    - swarm
    - tmux

- name: Configure Raspberry Pi 5
  hosts: raspberry-pi-5
  become: true
  module_defaults:
    community.docker.docker_stack:
      detach: false
  vars_files:
    - vault/caddy.yml
    - vault/blinko.yml
    - vault/bitwarden.yml
    - vault/davinci.yml
    - vault/karakeep.yml
    - vault/matrix.yml
    - vault/samba.yml
    - vault/stash.yml
    - vault/tailscale.yml
    - vault/woodpecker.yml
  roles:
    - caddy
    - actual
    - adguard
    - bitwarden
    - blinko
    - davinci
    - glance
    - heimdall
    - jellyfin
    - karakeep
    - matrix
    - n8n
    - nextcloud
    - openwebui
    - paperless
    - samba
    - sillytavern
    - stash
    - tailscale
    - woodpecker
