- name: Configure Swarm
  hosts: swarm
  become: true
  roles:
    - swarm
    - tmux

- name: Configure Raspberry Pi 4
  hosts: raspberry-pi-4
  become: true
  vars_files:
    - vault/caddy.yml
    - vault/bitwarden.yml
    - vault/davinci.yml
    - vault/karakeep.yml
    - vault/samba.yml
    - vault/stash.yml
    - vault/tailscale.yml
  roles:
    - caddy
    - adguard
    - bitwarden
    - davinci
    - heimdall
    - karakeep
    - n8n
    - nextcloud
    - samba
    - sillytavern
    - stash
    - tailscale
