networks:
  default:
    name: host
    external: true

volumes:
  config:

services:
  tailscale:
    image: tailscale/tailscale:v{{ tailscale_version }}
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TS_AUTHKEY={{ tailscale_auth_key }}
      - TS_USERSPACE=0
      - TS_ROUTES=192.168.0.0/24
      - TS_EXTRA_ARGS=--advertise-exit-node
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - config:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    deploy:
      placement:
        constraints:
          - node.hostname == {{ ansible_hostname }}
