- name: Set image tag
  ansible.builtin.set_fact:
    caddy_image_tag: "custom-{{ (lookup('file', role_path + '/files/Dockerfile') | hash('sha256'))[:7] }}"

- name: Build image
  ansible.builtin.include_tasks:
    file: build.yml

- name: Deploy stack
  community.docker.docker_stack:
    name: caddy
    compose: ["{{ lookup('template', 'compose.yaml') | from_yaml }}"]
  notify: Prune Docker images
