networks:
  default:
    name: caddy
    external: true

configs:
{% for item in lookup('fileglob', role_path + '/files/*.yml', wantlist=True) %}
  {{ item | basename | splitext | first }}:
    name: "glance_{{ item | basename | splitext | first }}_{{ (lookup('file', item) | hash('sha256'))[:7] }}"
    external: true
{% endfor %}

services:
  glance:
    image: "glanceapp/glance:v{{ glance_version }}"
    configs:
{% for item in lookup('fileglob', role_path + '/files/*.yml', wantlist=True) %}
      - source: "{{ item | basename | splitext | first }}"
        target: "/app/config/{{ item | basename }}"
{% endfor %}
    volumes:
      - /etc/localtime:/etc/localtime:ro
    deploy:
      labels:
        caddy: dash.echocharlie.xyz
        caddy.reverse_proxy: glance:8080
        caddy.import: dns
      placement:
        constraints:
          - node.hostname == {{ ansible_facts['hostname'] }}
