networks:
  default:
    name: caddy
    external: true

volumes:
  data:
  media:
  cache:

services:
  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:2.20.15@sha256:6c86cad803970ea782683a8e80e7403444c5bf3cf70de63b4d3c8e87500db92f
    environment:
      - PAPERLESS_URL=https://docs.echocharlie.xyz
      - PAPERLESS_REDIS=redis://redis:6379
      - PAPERLESS_TIKA_ENABLED=1
      - PAPERLESS_TIKA_ENDPOINT=http://tika:9998
      - PAPERLESS_TIKA_GOTENBERG_ENDPOINT=http://gotenberg:3000
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - /mnt/wd_elements/Data/Apps/Paperless:/usr/src/paperless/export
    deploy:
      labels:
        caddy: docs.echocharlie.xyz
        caddy.reverse_proxy: paperless:8000
        caddy.import: dns
      placement:
        constraints:
          - node.hostname == {{ ansible_facts['hostname'] }}

  redis:
    image: redis:8.6.1@sha256:315270d166080f537bbdf1b489b603aaaa213cb55a544acfa51feb7481abb1c0
    volumes:
      - cache:/data
    deploy:
      placement:
        constraints:
          - node.hostname == {{ ansible_facts['hostname'] }}

  tika:
    image: apache/tika:3.3.1.0@sha256:90b7fa1dc018434075fce9e1d9b88b1e3d0ea6979d0cf86e116c79a8073ae973
    deploy:
      placement:
        constraints:
          - node.hostname == {{ ansible_facts['hostname'] }}

  gotenberg:
    image: gotenberg/gotenberg:8.26.0@sha256:328551506b3dec3ff6381dd47e5cd72a44def97506908269e201a8fbfa1c12c0
    command: gotenberg --chromium-disable-javascript=true --chromium-allow-list=file:///tmp/.*
    deploy:
      placement:
        constraints:
          - node.hostname == {{ ansible_facts['hostname'] }}
