networks:
  default:
    name: caddy
    external: true

volumes:
  data:
  media:
  cache:

services:
  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:{{ paperless_version }}
    environment:
      - PAPERLESS_URL=https://docs.echocharlie.xyz
      - PAPERLESS_REDIS=redis://redis:6379
      - PAPERLESS_TIKA_ENABLED=1
      - PAPERLESS_TIKA_ENDPOINT=http://tika:9998
      - PAPERLESS_TIKA_GOTENBERG_ENDPOINT=http://gotenberg:3000
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - /mnt/wd_elements/Data/Apps/Paperless:/usr/src/paperless/export
    depends_on:
      - redis
      - tika
      - gotenberg
    deploy:
      labels:
        caddy: docs.echocharlie.xyz
        caddy.reverse_proxy: paperless:8000
        caddy.import: dns
      placement:
        constraints:
          - node.hostname == {{ ansible_hostname }}

  redis:
    image: redis:{{ paperless_redis_version }}
    volumes:
      - cache:/data
    deploy:
      placement:
        constraints:
          - node.hostname == {{ ansible_hostname }}

  tika:
    image: apache/tika:{{ paperless_tika_version }}
    deploy:
      placement:
        constraints:
          - node.hostname == {{ ansible_hostname }}

  gotenberg:
    image: gotenberg/gotenberg:{{ paperless_gotenberg_version }}
    command: gotenberg --chromium-disable-javascript=true --chromium-allow-list=file:///tmp/.*
    deploy:
      placement:
        constraints:
          - node.hostname == {{ ansible_hostname }}
