networks:
  default:
    name: caddy
    external: true

volumes:
  etc:
  lib:

services:
  samba:
    image: dperson/samba
    environment:
      USERID: 0
      GROUPID: 0
      SHARE: Data;/mnt;yes;no;no;all
      GLOBAL: hide files = $$RECYCLE.BIN/System Volume Information
      SMB: 1
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    volumes:
      - etc:/etc
      - lib:/var/lib/samba
      - /mnt/wd_elements:/mnt
    tmpfs:
      - /var/cache/samba
      - /var/log/samba
      - /run/samba
    deploy:
      placement:
        constraints:
          - node.hostname == {{ ansible_facts['hostname'] }}
