networks:
  default:
    name: caddy
    external: true

volumes:
  config:

services:
  bitwarden:
    image: vaultwarden/server:1.37.3@sha256:1587c45feaa479f1f5e8af3b00eded36bff77bcf1880cf8dbf0541706dd470e0
    environment:
      - "ADMIN_TOKEN={{ bitwarden_admin_token }}"
    volumes:
      - config:/data
    deploy:
      labels:
        caddy: pass.echocharlie.xyz
        caddy.reverse_proxy: bitwarden:80
        caddy.import: dns
      placement:
        constraints:
          - node.hostname == {{ ansible_facts['hostname'] }}
