networks:
  default:
    name: caddy
    external: true

volumes:
  config:

services:
  bitwarden:
    image: vaultwarden/server:1.37.1@sha256:ebdfe70701c60ac0c28c697e787cea767d7972940b786037b29fe0d507f821e8
    environment:
      - "ADMIN_TOKEN={{ bitwarden_admin_token }}"
    volumes:
      - config:/data
    deploy:
      labels:
        caddy: pass.echocharlie.xyz
        caddy.reverse_proxy: bitwarden:80
        caddy.import: dns
      placement:
        constraints:
          - node.hostname == {{ ansible_facts['hostname'] }}
