- name: Create config
  community.docker.docker_config:
    name: "openwebui_config_{{ (lookup('file', role_path + '/files/custom.css') | hash('sha256'))[:7] }}"
    data: "{{ lookup('file', role_path + '/files/custom.css') }}"

- name: Deploy stack
  community.docker.docker_stack:
    name: openwebui
    compose: ["{{ lookup('template', 'stack.yml') | from_yaml }}"]
  notify: Prune Docker images
