networks:
  default:
    name: caddy
    external: true

volumes:
  config:

services:
  heimdall:
    image: linuxserver/heimdall:2.7.6@sha256:536eb14f068fe3f052b92f94ca606db689d1d1b79b5408d1242c12e882e4ed66
    volumes:
      - config:/config
    deploy:
      labels:
        caddy: echocharlie.xyz, www.echocharlie.xyz
        caddy.reverse_proxy: heimdall:80
        caddy.import: dns
      placement:
        constraints:
          - node.hostname == {{ ansible_facts['hostname'] }}
