networks:
  default:
    name: caddy
    external: true

volumes:
  config:

services:
  heimdall:
    image: linuxserver/heimdall:2.8.2@sha256:cec3abe123f43bb07c16373065669218473d219f401885b3c876b4c4993f3f4b
    volumes:
      - config:/config
    deploy:
      labels:
        caddy: echocharlie.xyz, www.echocharlie.xyz
        caddy.reverse_proxy: heimdall:80
        caddy.import: dns
      placement:
        constraints:
          - node.hostname == {{ ansible_facts['hostname'] }}
