networks:
  default:
    name: caddy
    external: true

volumes:
  config:

services:
  adguard:
    image: adguard/adguardhome:v0.107.79@sha256:aba9e3bf0613be3ba3755e1fc311b126e2c24bec25e18b6483894a88283074f0
    volumes:
      - config:/opt/adguardhome/conf
      - config:/opt/adguardhome/work
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    deploy:
      labels:
        caddy: dns.echocharlie.xyz
        caddy.reverse_proxy: adguard:80
        caddy.import: dns
      placement:
        constraints:
          - node.hostname == {{ ansible_facts['hostname'] }}
