networks:
  default:
    name: caddy
    external: true

volumes:
  config:

services:
  adguard:
    image: adguard/adguardhome:v0.107.74
    volumes:
      - config:/opt/adguardhome/conf
      - config:/opt/adguardhome/work
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    deploy:
      labels:
        caddy: dns.echocharlie.xyz
        caddy.reverse_proxy: adguard:80
        caddy.import: dns
      placement:
        constraints:
          - node.hostname == {{ ansible_facts['hostname'] }}
