networks:
  default:
    name: caddy
    external: true

volumes:
  config:
  data:

services:
  nextcloud:
    image: linuxserver/nextcloud:33.0.5@sha256:4de5f8f400f06690751c2f1a07d8bedb3eec084351e24f5ba074198da080be1c
    volumes:
      - config:/config
      - data:/data
    deploy:
      labels:
        caddy: cloud.echocharlie.xyz
        caddy.reverse_proxy: nextcloud:443
        caddy.reverse_proxy.transport: http
        caddy.reverse_proxy.transport.tls_insecure_skip_verify:
        caddy.redir_1: /.well-known/carddav /remote.php/dav 301
        caddy.redir_2: /.well-known/caldav /remote.php/dav 301
        caddy.redir_3: /.well-known/webfinger /index.php/.well-known/webfinger 301
        caddy.redir_4: /.well-known/nodeinfo /index.php/.well-known/nodeinfo 301
        caddy.header: Strict-Transport-Security "max-age=15552000; includeSubDomains"
        caddy.import: dns
      placement:
        constraints:
          - node.hostname == {{ ansible_facts['hostname'] }}
