networks:
  default:
    name: caddy
    external: true

volumes:
  config:
  cache:

services:
  jellyfin:
    image: jellyfin/jellyfin:10.11.11@sha256:aefb67e6a7ff1debdd154a78a7bbb780fd0c873d8639210a7f6a2016ad2b35db
    volumes:
      - config:/config
      - cache:/cache
      - /mnt/wd_elements/Media:/media
    deploy:
      labels:
        caddy: tv.echocharlie.xyz
        caddy.reverse_proxy: jellyfin:8096
        caddy.import: dns
      placement:
        constraints:
          - node.hostname == {{ ansible_facts['hostname'] }}
