networks:
  default:
    name: caddy
    external: true

volumes:
  data:

services:
  n8n:
    image: n8nio/n8n:{{ n8n_version }}
    environment:
      - N8N_HOST=cron.echocharlie.xyz
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://cron.echocharlie.xyz/
      - GENERIC_TIMEZONE=Europe/London
    volumes:
      - data:/home/node/.n8n
    deploy:
      labels:
        caddy: cron.echocharlie.xyz
        caddy.reverse_proxy: n8n:5678
        caddy.import: dns
      placement:
        constraints:
          - node.hostname == {{ ansible_hostname }}
