networks:
  default:
    name: caddy
    external: true

volumes:
  data:

services:
  davinci:
    image: postgres:13.23
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER={{ davinci_user.username }}
      - POSTGRES_PASSWORD={{ davinci_user.password }}
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      placement:
        constraints:
          - node.hostname == {{ ansible_facts['hostname'] }}
