networks:
  default:
    name: caddy
    external: true

volumes:
  data:

services:
  actual:
    image: actualbudget/actual-server:26.9.0@sha256:552beab3dec8c93d46b8b9245612d63c3f123b8a45063a474f53e229b17621d3
    volumes:
      - data:/data
    deploy:
      labels:
        caddy: money.echocharlie.xyz
        caddy.reverse_proxy: actual:5006
        caddy.import: dns
      placement:
        constraints:
          - node.hostname == {{ ansible_facts['hostname'] }}
