networks:
  default:
    name: caddy
    external: true

volumes:
  config:

services:
  stash:
    image: rclone/rclone:1.74.1@sha256:eb8788b795f0009324e9572b0e2acb9b56885327c2746b07d67a9d3b893a6602
    command: "serve webdav --addr :80 --user {{ stash_user.username }} --pass {{ stash_user.password }} Stash:"
    environment:
      - PHP_TZ=Europe/London
      - PUID=0
      - PGID=0
    volumes:
      - config:/config/rclone
      - /mnt/wd_elements:/data
    tmpfs:
      - /logs
    deploy:
      labels:
        caddy: stash.echocharlie.xyz
        caddy.reverse_proxy: stash:80
        caddy.import: dns
      placement:
        constraints:
          - node.hostname == {{ ansible_facts['hostname'] }}
